# File: .github/workflows/nextjs.yml
name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        # Use --legacy-peer-deps to bypass the peer dependency conflicts
        run: npm install --legacy-peer-deps

      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local

      # Debug: Check next.config.mjs content
      - name: Check Next.js config
        run: cat next.config.mjs || echo "next.config.mjs not found"

      - name: Build Next.js application
        run: npm run build

      # Debug: List directories to see where the build output is
      - name: List directories
        run: ls -la

      # Create out directory if it doesn't exist
      - name: Create out directory if needed
        run: mkdir -p out

      # Create .nojekyll file
      - name: Add .nojekyll file
        run: touch out/.nojekyll

      # Deploy directly to GitHub Pages branch
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # The folder the action should deploy
          branch: gh-pages # The branch the action should deploy to
