# File: .github/workflows/nextjs.yml
name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local

      # Fix the TypeScript error in SetupStorage component
      - name: Fix SetupStorage component
        run: |
          cat > app/admin/dashboard/setup-storage.tsx << 'EOL'
          "use client"

          import { useState } from "react"
          import { getSupabaseBrowser } from "@/lib/supabase"
          import { Button } from "@/components/ui/button"
          import { Database } from 'lucide-react'

          // Add the onClose prop to the component's props
          interface SetupStorageProps {
            onClose?: () => void;  // Make it optional with ?
          }

          export default function SetupStorage({ onClose }: SetupStorageProps) {
            const [loading, setLoading] = useState(false)
            const [message, setMessage] = useState("")
            const supabase = getSupabaseBrowser()

            const setupStorage = async () => {
              try {
                setLoading(true)
                setMessage("Setting up storage buckets and policies...")

                // Create the buckets if they don't exist
                const { error: bucketsError } = await supabase.rpc("create_storage_buckets")
                if (bucketsError) {
                  console.error("Error creating buckets:", bucketsError)
                  setMessage(`Error creating buckets: ${bucketsError.message}`)
                  return
                }

                // Set up storage policies
                const { error: policiesError } = await supabase.rpc("create_storage_policies")
                if (policiesError) {
                  console.error("Error creating policies:", policiesError)
                  setMessage(`Error creating policies: ${policiesError.message}`)
                  return
                }

                // Manually update bucket settings to be public
                const { data: buckets } = await supabase.storage.listBuckets()

                for (const bucket of buckets || []) {
                  if (bucket.name === "profile-picture" || bucket.name === "backgrounds" || bucket.name === "songs") {
                    const { error } = await supabase.storage.updateBucket(bucket.name, {
                      public: true,
                    })

                    if (error) {
                      console.error(`Failed to update bucket ${bucket.name}:`, error)
                    }
                  }
                }

                setMessage("Storage setup complete! Buckets and policies have been configured.")
                
                // If onClose is provided, call it after a delay to show the success message
                if (onClose) {
                  setTimeout(() => {
                    onClose();
                  }, 2000);
                }
              } catch (error: any) {
                console.error("Error setting up storage:", error)
                setMessage(`Error: ${error.message}`)
              } finally {
                setLoading(false)
              }
            }

            return (
              <div className="p-4 border border-gray-700 rounded-md">
                <h3 className="text-md font-semibold mb-3">Storage Setup</h3>
                <p className="text-sm text-gray-400 mb-3">
                  If you're having issues with uploads, run this setup to configure storage buckets and policies.
                </p>
                <div className="flex justify-between">
                  <Button onClick={setupStorage} disabled={loading} className="bg-purple-700 hover:bg-purple-600 text-white">
                    <Database className={`h-4 w-4 mr-2 ${loading ? "animate-pulse" : ""}`} />
                    {loading ? "Setting up..." : "Setup Storage Buckets"}
                  </Button>
                  
                  {/* Add a close button if onClose is provided */}
                  {onClose && (
                    <Button onClick={onClose} variant="outline" className="ml-2">
                      Cancel
                    </Button>
                  )}
                </div>

                {message && (
                  <div className="mt-4 p-3 bg-gray-800 rounded text-sm">
                    <pre className="whitespace-pre-wrap">{message}</pre>
                  </div>
                )}
              </div>
            )
          }
          EOL

      # Update next.config.mjs to ensure static export
      - name: Update Next.js config
        run: |
          cat > next.config.mjs << 'EOL'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            reactStrictMode: true,
            images: {
              unoptimized: true,
            },
            output: 'export',
          };

          export default nextConfig;
          EOL

      - name: Build Next.js application
        run: npm run build

      # Deploy using GitHub Pages action
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          clean: true
